config/routes.rb
Rails.application.routes.draw do
  get 'products/add'
  get 'products/get_list'
  post 'products/create'

  get 'discussions/mine'
  devise_for :users, controllers: {registrations: 'registrations'}
  get 'visitors/index'
  resources :categories, only: :index
  resources :discussions, only: [:index, :new, :create, :show]
  resources :messages, only: [:new]

   root "visitors#index"

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  parent_id  :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :products
  has_many :subcategories, foreign_key: 'parent_id', class_name: 'Category', counter_cache: :subcategories_count
  belongs_to :parent, class_name: 'Category'

  validates :parent_id, :name, presence: true

  scope :main_categories, ->  { where 'parent_id = ?', 0 }
end

app/models/discussion.rb
# == Schema Information
#
# Table name: discussions
#
#  id         :integer          not null, primary key
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Discussion < ActiveRecord::Base
  acts_as_taggable

  validates :product_id, :user_id, presence: true

  belongs_to :product
  belongs_to :user

  has_many :messages

  accepts_nested_attributes_for :messages

  def question
    messages.first
  end
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id            :integer          not null, primary key
#  discussion_id :integer
#  content       :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Message < ActiveRecord::Base
  belongs_to :discussion
  belongs_to :user
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Product < ActiveRecord::Base
  has_many :users, through: :product_users
  has_many :product_users
  has_many :discussions
  belongs_to :category

  validates :name, :category_id, presence: true
end

app/models/product_user.rb
# == Schema Information
#
# Table name: product_users
#
#  id         :integer          not null, primary key
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class ProductUser < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :product, :user, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :product_users
  has_many :products, through: :product_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protected

  def after_sign_in_path_for(resource)
    discussions_mine_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  expose(:categories) { Category.main_categories.includes(:subcategories) }
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :index]

  expose(:discussions)
  expose(:discussion, attributes: :discussion_params)

  def create
    discussion.user = current_user
    if discussion.save
      redirect_to discussion_path(discussion), notice: I18n.t('shared.created', resource: 'Discussion')
    else
      render :new
    end
  end

  private
  def discussion_params
    params.require(:discussion).permit(:tag_list, { messages_attributes: :content }, :product_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def add
    @category = Category.all.includes(:subcategories)
    @product = Product.all.order(:name)
    @subcategories = Category.all.where(parent_id: 0)
  end

  def create
  end

  def get_list
    respond_to do |format|
      format.json { render json: Product.where('name ILIKE ?', "#{params[:q]}%").all }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
  end

  def new
    @categories = Category.all.includes(:subcategories)
    super
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/categories/_category.haml
%a.list-group-item{ href: "#", "data-link": category.name.parameterize }
  = category.name
  %span.badge
    = category.subcategories.size

app/views/categories/_subcategory.haml
.list-group-item
  = subcategory.name

app/views/categories/index.haml
%h1 Categories
.col-md-6
  .main-categories
    - categories.each do |category|
      = render partial: 'category', object: category
.col-md-6
  .sub-categories
    - categories.each do |category|
      .sub-category{ id: category.name.parameterize }
        - category.subcategories.each do |subcategory|
          = render partial: 'subcategory', object: subcategory

app/views/discussions/_discussion.html.haml
= link_to(content_tag(:span, discussion.question.content, class: 'question-before-badge') + content_tag(:span, discussion.messages.size, class: 'badge'), discussion, class: 'list-group-item')

app/views/discussions/_message.html.haml
%div{class: "#{class_name}"}
  = message.content
  %br
  .message-info
    = mail_to message.user.email

app/views/discussions/index.html.haml
%h1 Discussions
.col-md-12
  - discussions.each do |discussion|
    = render partial: 'discussion', object: discussion

app/views/discussions/mine.html.haml
%h1 Discussions#mine
%p Find me in app/views/discussions/mine.html.haml

app/views/discussions/new.html.haml
%h1 Ask a Question
.col-md-6
  = simple_form_for discussion do |f|
    = f.input :product_id, collection: Product.all
    = f.simple_fields_for :messages, discussion.messages.build do |m|
      = m.input :content
    = f.button :submit, 'Ask question'

app/views/discussions/show.html.haml
%h1 Discussion
.col-md-12
  = render partial: 'message', object: discussion.question, locals: { class_name: 'question' }
  - discussion.messages.drop(1).each do |message|
    = render partial: 'message', object: message, locals: { class_name: 'message' }

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Know Things', root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-left
          %li
            = link_to 'Ask a Question',  new_discussion_path
          %li
            = link_to discussions_mine_path do
              Questions to me
              %span.label.label-danger.label-as-badge 3
          %li
            = link_to 'Browse Questions', discussions_path
        %ul.nav.navbar-nav.navbar-right
          %form.navbar-form.navbar-left{role: "search"}
            .form-group
              %input.form-control{placeholder: "Search", type: "text"}/
          %li
            = link_to 'Logout', destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-left
          %li
            = link_to 'Make a Question', new_discussion_path
          %li
            = link_to 'Browse Questions', discussions_path
        %ul.nav.navbar-nav.navbar-right
          %form.navbar-form.navbar-left{role: "search"}
            .form-group
              %input.form-control{placeholder: "Search", type: "text"}/
          %li
            = link_to 'Sign in', new_user_session_path
          %li
            = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title KnowThings
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    %main
      .col-lg-12
        = render 'layouts/messages'
        .container
          = yield

app/views/messages/new.html.haml
%h1 Messages#new
%p Find me in app/views/messages/new.html.haml

app/views/products/add.html.haml
= form_tag(products_create_path, method: :post, class: 'js-add-product-form' ) do
  %button.btn.btn-large.btn-success{:type => "button", id: 'js_add_product'} +
  .js-product-selector
    %br
    = grouped_collection_select(:subcategory, :parent_id, @category, :subcategories, :name, :id, :name, {}, { class: 'subcategory_parent_id' } )
    %br
    .product_id
    %br

  .js-moar-products

  %br
  %button.btn.btn-large.btn-success{ type: "submit" } Save

app/views/visitors/index.html.haml
.row
  .col-lg-12
    .bs-component
      .jumbotron
        %h1 Know Things App
        %p Share knowledge about things in effective way
        %p
          = link_to 'Join now!', new_user_registration_path, class: 'btn btn-primary btn-lg'